on :
    push :
        branches : 
            - main
            - "*"
        tags : 
            - "v*"
            - "latest"
            - "stable"
        
    pull_request :
        types : 
            - opened
        branches :
            - "*"
        paths : 
          - "**.ts"



jobs : 
    build-andorid : 
        runs-on : ubuntu-latest

        steps : 
            - name : Checkout to repo 
              uses : actions/checkout@v3

            - name : Setup Java
              uses : actions/setup-java@v3
              with :
                distribution : 'zulu'
                java-version : '11'
            
            - name : Setup Node
              uses : actions/setup-node@v3
              with :
                node-version: 18
            
            - name : install yarn 
              run : npm i -g yarn

            - name : Install deps
              run : yarn
              
            - name : make executable
              run : chmod +x gradlew
              working-directory : android

            - name : Build Release with gradle
              run : ./gradlew assembleRelease
              working-directory : android
        
